"""add messages table

Revision ID: 80ff4f539839
Revises: 3b84724c64e4
Create Date: 2024-06-10 10:38:19.967529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ff4f539839'
down_revision = '3b84724c64e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('messages', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
